services:
  updater:
    build: .
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}  # Ensure this is set in your .env file or environment
      GITHUB_EMAIL: ${GITHUB_EMAIL}  # Ensure this is set in your .env file or environment
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit log file to 10 MB
        max-file: "3"    # Keep at most 3 log files (rotates after exceeding max-size)